<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>initialize decision</name>
  <uuid>8e8bf890-5154-47b4-8e81-c4ef64509e06</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to IT201 ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
