<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>recompute FAGI (temp CISS FAGI)</name>
  <uuid>85b85edc-e3e7-4b07-a178-6fb3fefc8886</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    IT558 is not null 
    and there is no CISS Code in the CISS Codes of IT201 where the id of this CISS Code is C018, 
    and the TEMP_CISS_FAGI of IT201 is Present 
then
	set the value of the FEDAGI_RCOMP_AMT of decision to the value of the FEDAGI_AMT of IT201 ;    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
