<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>recompute FAGI (no temp CISS FAGI)</name>
  <uuid>46584f21-0151-492b-904b-23505b51ca89</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    IT558 is not null
    and there is no CISS Code in the CISS Codes of decision where the id of this CISS Code is C018, 
    and the TEMP_CISS_FAGI of decision is Absent 
then
	set the value of the FEDAGI_RCOMP_AMT of decision to 
    		max ( the claimed of the FEDAGI_RCOMP_AMT of decision , the value of the FEDAGI_AMT of decision ); ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
