<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set FAGI</name>
  <uuid>a160cb06-0556-4ba4-95b9-887f112597cd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the value of the FEDAGI_AMT of decision to the claimed of the FEDAGI_AMT of IT201 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
