<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set RSDT_CR_AMT</name>
  <uuid>853e5234-a4a3-4b5a-8caf-415eaa6e203c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
     the absolute value of (the claimed of the RSDT_CR_AMT of decision - the TEMP_RES_CR of decision) 
     	is more than the PTRT_COMP_TOL_AMOUNT of 'reference data' 
then
	set the value of the RSDT_CR_AMT of decision to 
    	min (the claimed of the RSDT_CR_AMT of decision, the TEMP_RES_CR of decision);
	add A027 to the codes of the RSDT_CR_AMT of decision ; 
    set the NY_TX_ADJ_IND of the globals of decision to Present ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
